export const USER_EXISTS = `USER EXISTS ALREADY. KINDLY TRY LOGGING IN`;
export const ACCOUNT_CREATION_SUCCESS = `YOUR ACCOUNT HAS BEEN CREATED SUCCESSFULLY`
export const USER_NOT_FOUND = `THE USER DOES NOT EXISTS KINDLY PLEASE CREATE AN ACCOUNT FIRST`
export const PASSWORD_MISMATCH = `PLEASE ENTER VALID PASSWORD`